### ISSUE TITLE
On click or hover, show more details about each time slot

### ISSUE THREAD

**Issue by sujunglee** [cs394-w20/find-a-time#14]
- [x] Make a window pop up on click or hover of a time slot
- [ ] Display info about the specific people who are available and unavailable in that slot

**Comment by jdanene** [comment]
finished EventInvite, think i would be nice to add a button that appears s.t user can send event invite on hover. EventInvite is kinda hidden since u need to click the calendar for it to show up, this makes less hiddn

**Comment by sujunglee** [comment]
Gotcha, I can add a button that triggers EventInvite!

**Comment by jdanene** [comment]
For YourEvents i added something that shows more info about the user, the code is [here](https://github.com/cs394-w20/find-a-time/blob/master/src/views/YourEvents/components/SimpleDialog.js)
It's when u click the little arrow
<img width="1381" alt="Screen Shot 2020-02-01 at 2 45 03 AM" src="https://user-images.githubusercontent.com/12655844/73589545-ebceb180-449c-11ea-9ab0-0687fb4bceb8.png">

helpful 4 second bullet pt

**Comment by sujunglee** [comment]
Awesome, looks great! I'll add additional info for each of the time slots as well
