### ISSUE TITLE
[NavBar] Add signout feature to the navbar

### ISSUE THREAD

**Issue by jdanene** [cs394-w20/find-a-time#68]
instead of having `account` in the pic below you could have `sign out` and skip implementing a drop down. 
<img width="477" alt="Screen Shot 2020-02-01 at 1 28 47 AM" src="https://user-images.githubusercontent.com/12655844/73629818-dcc13e00-4619-11ea-9a00-b406589a73b1.png">
<img width="503" alt="Screen Shot 2020-02-01 at 1 28 42 AM" src="https://user-images.githubusercontent.com/12655844/73629819-dcc13e00-4619-11ea-930b-f3bf6ccb9c26.png">

**Comment by szaslan** [comment]
committed earlier, closing
